version: 0.1.0
name: rails-app-heroku-stack
description: |
  This stack will generate a Rails App and setup a workflow to deploy it to Heroku
branding:
  icon: 'cloud'
  color: 'purple'

inputs:
  - name: RUBY_VERSION
    default: 3.0.2
    description: The version of ruby to use

  - name: RAILS_VERSION
    default: 6.1.4.1
    description: The version of rails to use

  - name: RAILS_RC_URL
    required: false
    description: (Optional) A URL to a .railsrc file

  - name: HEROKU_EMAIL
    description: Heroku email
    is-secret: true

  - name: HEROKU_API_KEY
    description: Heroku api key
    is-secret: true

  - name: HEROKU_APP_NAME
    description: (Optional) Heroku app name
