name: sundar addition check
description: test some stuff

github-apps:
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
- slug: backhub
init:
 uses: "setup.yml"
